package com.mini.shop.dao.generate;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;

public class PmsProductDTOWithBLOBs extends PmsProductDTO implements Serializable {
    private String description;

    private String detailDesc;

    private String detailHtml;

    private String detailMobileHtml;

    private static final long serialVersionUID = 1L;

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public String getDetailDesc() {
        return detailDesc;
    }

    public void setDetailDesc(String detailDesc) {
        this.detailDesc = detailDesc == null ? null : detailDesc.trim();
    }

    public String getDetailHtml() {
        return detailHtml;
    }

    public void setDetailHtml(String detailHtml) {
        this.detailHtml = detailHtml == null ? null : detailHtml.trim();
    }

    public String getDetailMobileHtml() {
        return detailMobileHtml;
    }

    public void setDetailMobileHtml(String detailMobileHtml) {
        this.detailMobileHtml = detailMobileHtml == null ? null : detailMobileHtml.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table pms_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        brandId("brand_id", "brandId", "BIGINT", false),
        productCategoryId("product_category_id", "productCategoryId", "BIGINT", false),
        feightTemplateId("feight_template_id", "feightTemplateId", "BIGINT", false),
        productAttributeCategoryId("product_attribute_category_id", "productAttributeCategoryId", "BIGINT", false),
        name("name", "name", "VARCHAR", true),
        pic("pic", "pic", "VARCHAR", false),
        productSn("product_sn", "productSn", "VARCHAR", false),
        deleteStatus("delete_status", "deleteStatus", "INTEGER", false),
        publishStatus("publish_status", "publishStatus", "INTEGER", false),
        newStatus("new_status", "newStatus", "INTEGER", false),
        recommandStatus("recommand_status", "recommandStatus", "INTEGER", false),
        verifyStatus("verify_status", "verifyStatus", "INTEGER", false),
        sort("sort", "sort", "INTEGER", false),
        sale("sale", "sale", "INTEGER", false),
        price("price", "price", "DECIMAL", false),
        promotionPrice("promotion_price", "promotionPrice", "DECIMAL", false),
        giftGrowth("gift_growth", "giftGrowth", "INTEGER", false),
        giftPoint("gift_point", "giftPoint", "INTEGER", false),
        usePointLimit("use_point_limit", "usePointLimit", "INTEGER", false),
        subTitle("sub_title", "subTitle", "VARCHAR", false),
        originalPrice("original_price", "originalPrice", "DECIMAL", false),
        stock("stock", "stock", "INTEGER", false),
        lowStock("low_stock", "lowStock", "INTEGER", false),
        unit("unit", "unit", "VARCHAR", false),
        weight("weight", "weight", "DECIMAL", false),
        previewStatus("preview_status", "previewStatus", "INTEGER", false),
        serviceIds("service_ids", "serviceIds", "VARCHAR", false),
        keywords("keywords", "keywords", "VARCHAR", false),
        note("note", "note", "VARCHAR", false),
        albumPics("album_pics", "albumPics", "VARCHAR", false),
        detailTitle("detail_title", "detailTitle", "VARCHAR", false),
        promotionStartTime("promotion_start_time", "promotionStartTime", "TIMESTAMP", false),
        promotionEndTime("promotion_end_time", "promotionEndTime", "TIMESTAMP", false),
        promotionPerLimit("promotion_per_limit", "promotionPerLimit", "INTEGER", false),
        promotionType("promotion_type", "promotionType", "INTEGER", false),
        brandName("brand_name", "brandName", "VARCHAR", false),
        productCategoryName("product_category_name", "productCategoryName", "VARCHAR", false),
        description("description", "description", "LONGVARCHAR", false),
        detailDesc("detail_desc", "detailDesc", "LONGVARCHAR", false),
        detailHtml("detail_html", "detailHtml", "LONGVARCHAR", false),
        detailMobileHtml("detail_mobile_html", "detailMobileHtml", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pms_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}