package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.CmsHelpDTO;
import com.mini.shop.dao.generate.CmsHelpDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsHelpDTOMapper {
    long countByExample(CmsHelpDTOExample example);

    int deleteByExample(CmsHelpDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CmsHelpDTO record);

    int insertSelective(CmsHelpDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsHelpDTO selectOneByExample(CmsHelpDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsHelpDTO selectOneByExampleWithBLOBs(CmsHelpDTOExample example);

    List<CmsHelpDTO> selectByExampleWithBLOBs(CmsHelpDTOExample example);

    List<CmsHelpDTO> selectByExample(CmsHelpDTOExample example);

    CmsHelpDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CmsHelpDTO record, @Param("example") CmsHelpDTOExample example);

    int updateByExampleWithBLOBs(@Param("record") CmsHelpDTO record, @Param("example") CmsHelpDTOExample example);

    int updateByExample(@Param("record") CmsHelpDTO record, @Param("example") CmsHelpDTOExample example);

    int updateByPrimaryKeySelective(CmsHelpDTO record);

    int updateByPrimaryKeyWithBLOBs(CmsHelpDTO record);

    int updateByPrimaryKey(CmsHelpDTO record);
}