package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.CmsMemberReportDTO;
import com.mini.shop.dao.generate.CmsMemberReportDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsMemberReportDTOMapper {
    long countByExample(CmsMemberReportDTOExample example);

    int deleteByExample(CmsMemberReportDTOExample example);

    int insert(CmsMemberReportDTO record);

    int insertSelective(CmsMemberReportDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_member_report
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsMemberReportDTO selectOneByExample(CmsMemberReportDTOExample example);

    List<CmsMemberReportDTO> selectByExample(CmsMemberReportDTOExample example);

    int updateByExampleSelective(@Param("record") CmsMemberReportDTO record, @Param("example") CmsMemberReportDTOExample example);

    int updateByExample(@Param("record") CmsMemberReportDTO record, @Param("example") CmsMemberReportDTOExample example);
}