package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.CmsPrefrenceAreaDTO;
import com.mini.shop.dao.generate.CmsPrefrenceAreaDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsPrefrenceAreaDTOMapper {
    long countByExample(CmsPrefrenceAreaDTOExample example);

    int deleteByExample(CmsPrefrenceAreaDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CmsPrefrenceAreaDTO record);

    int insertSelective(CmsPrefrenceAreaDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_prefrence_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsPrefrenceAreaDTO selectOneByExample(CmsPrefrenceAreaDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_prefrence_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsPrefrenceAreaDTO selectOneByExampleWithBLOBs(CmsPrefrenceAreaDTOExample example);

    List<CmsPrefrenceAreaDTO> selectByExampleWithBLOBs(CmsPrefrenceAreaDTOExample example);

    List<CmsPrefrenceAreaDTO> selectByExample(CmsPrefrenceAreaDTOExample example);

    CmsPrefrenceAreaDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CmsPrefrenceAreaDTO record, @Param("example") CmsPrefrenceAreaDTOExample example);

    int updateByExampleWithBLOBs(@Param("record") CmsPrefrenceAreaDTO record, @Param("example") CmsPrefrenceAreaDTOExample example);

    int updateByExample(@Param("record") CmsPrefrenceAreaDTO record, @Param("example") CmsPrefrenceAreaDTOExample example);

    int updateByPrimaryKeySelective(CmsPrefrenceAreaDTO record);

    int updateByPrimaryKeyWithBLOBs(CmsPrefrenceAreaDTO record);

    int updateByPrimaryKey(CmsPrefrenceAreaDTO record);
}