package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.CmsSubjectCategoryDTO;
import com.mini.shop.dao.generate.CmsSubjectCategoryDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsSubjectCategoryDTOMapper {
    long countByExample(CmsSubjectCategoryDTOExample example);

    int deleteByExample(CmsSubjectCategoryDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CmsSubjectCategoryDTO record);

    int insertSelective(CmsSubjectCategoryDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsSubjectCategoryDTO selectOneByExample(CmsSubjectCategoryDTOExample example);

    List<CmsSubjectCategoryDTO> selectByExample(CmsSubjectCategoryDTOExample example);

    CmsSubjectCategoryDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CmsSubjectCategoryDTO record, @Param("example") CmsSubjectCategoryDTOExample example);

    int updateByExample(@Param("record") CmsSubjectCategoryDTO record, @Param("example") CmsSubjectCategoryDTOExample example);

    int updateByPrimaryKeySelective(CmsSubjectCategoryDTO record);

    int updateByPrimaryKey(CmsSubjectCategoryDTO record);
}