package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.CmsSubjectCommentDTO;
import com.mini.shop.dao.generate.CmsSubjectCommentDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsSubjectCommentDTOMapper {
    long countByExample(CmsSubjectCommentDTOExample example);

    int deleteByExample(CmsSubjectCommentDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CmsSubjectCommentDTO record);

    int insertSelective(CmsSubjectCommentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsSubjectCommentDTO selectOneByExample(CmsSubjectCommentDTOExample example);

    List<CmsSubjectCommentDTO> selectByExample(CmsSubjectCommentDTOExample example);

    CmsSubjectCommentDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CmsSubjectCommentDTO record, @Param("example") CmsSubjectCommentDTOExample example);

    int updateByExample(@Param("record") CmsSubjectCommentDTO record, @Param("example") CmsSubjectCommentDTOExample example);

    int updateByPrimaryKeySelective(CmsSubjectCommentDTO record);

    int updateByPrimaryKey(CmsSubjectCommentDTO record);
}