package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.CmsTopicCommentDTO;
import com.mini.shop.dao.generate.CmsTopicCommentDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTopicCommentDTOMapper {
    long countByExample(CmsTopicCommentDTOExample example);

    int deleteByExample(CmsTopicCommentDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CmsTopicCommentDTO record);

    int insertSelective(CmsTopicCommentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsTopicCommentDTO selectOneByExample(CmsTopicCommentDTOExample example);

    List<CmsTopicCommentDTO> selectByExample(CmsTopicCommentDTOExample example);

    CmsTopicCommentDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CmsTopicCommentDTO record, @Param("example") CmsTopicCommentDTOExample example);

    int updateByExample(@Param("record") CmsTopicCommentDTO record, @Param("example") CmsTopicCommentDTOExample example);

    int updateByPrimaryKeySelective(CmsTopicCommentDTO record);

    int updateByPrimaryKey(CmsTopicCommentDTO record);
}