package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.CmsTopicDTO;
import com.mini.shop.dao.generate.CmsTopicDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTopicDTOMapper {
    long countByExample(CmsTopicDTOExample example);

    int deleteByExample(CmsTopicDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CmsTopicDTO record);

    int insertSelective(CmsTopicDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsTopicDTO selectOneByExample(CmsTopicDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CmsTopicDTO selectOneByExampleWithBLOBs(CmsTopicDTOExample example);

    List<CmsTopicDTO> selectByExampleWithBLOBs(CmsTopicDTOExample example);

    List<CmsTopicDTO> selectByExample(CmsTopicDTOExample example);

    CmsTopicDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CmsTopicDTO record, @Param("example") CmsTopicDTOExample example);

    int updateByExampleWithBLOBs(@Param("record") CmsTopicDTO record, @Param("example") CmsTopicDTOExample example);

    int updateByExample(@Param("record") CmsTopicDTO record, @Param("example") CmsTopicDTOExample example);

    int updateByPrimaryKeySelective(CmsTopicDTO record);

    int updateByPrimaryKeyWithBLOBs(CmsTopicDTO record);

    int updateByPrimaryKey(CmsTopicDTO record);
}