package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.OmsCompanyAddressDTO;
import com.mini.shop.dao.generate.OmsCompanyAddressDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsCompanyAddressDTOMapper {
    long countByExample(OmsCompanyAddressDTOExample example);

    int deleteByExample(OmsCompanyAddressDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(OmsCompanyAddressDTO record);

    int insertSelective(OmsCompanyAddressDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_company_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OmsCompanyAddressDTO selectOneByExample(OmsCompanyAddressDTOExample example);

    List<OmsCompanyAddressDTO> selectByExample(OmsCompanyAddressDTOExample example);

    OmsCompanyAddressDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") OmsCompanyAddressDTO record, @Param("example") OmsCompanyAddressDTOExample example);

    int updateByExample(@Param("record") OmsCompanyAddressDTO record, @Param("example") OmsCompanyAddressDTOExample example);

    int updateByPrimaryKeySelective(OmsCompanyAddressDTO record);

    int updateByPrimaryKey(OmsCompanyAddressDTO record);
}