package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.OmsCartItemDTO;
import com.mini.shop.dao.generate.OmsCartItemDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsCartItemDTOMapper {
    long countByExample(OmsCartItemDTOExample example);

    int deleteByExample(OmsCartItemDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(OmsCartItemDTO record);

    int insertSelective(OmsCartItemDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OmsCartItemDTO selectOneByExample(OmsCartItemDTOExample example);

    List<OmsCartItemDTO> selectByExample(OmsCartItemDTOExample example);

    OmsCartItemDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") OmsCartItemDTO record, @Param("example") OmsCartItemDTOExample example);

    int updateByExample(@Param("record") OmsCartItemDTO record, @Param("example") OmsCartItemDTOExample example);

    int updateByPrimaryKeySelective(OmsCartItemDTO record);

    int updateByPrimaryKey(OmsCartItemDTO record);
}