package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.OmsOrderDTO;
import com.mini.shop.dao.generate.OmsOrderDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsOrderDTOMapper {
    long countByExample(OmsOrderDTOExample example);

    int deleteByExample(OmsOrderDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(OmsOrderDTO record);

    int insertSelective(OmsOrderDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OmsOrderDTO selectOneByExample(OmsOrderDTOExample example);

    List<OmsOrderDTO> selectByExample(OmsOrderDTOExample example);

    OmsOrderDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") OmsOrderDTO record, @Param("example") OmsOrderDTOExample example);

    int updateByExample(@Param("record") OmsOrderDTO record, @Param("example") OmsOrderDTOExample example);

    int updateByPrimaryKeySelective(OmsOrderDTO record);

    int updateByPrimaryKey(OmsOrderDTO record);
}