package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.OmsOrderReturnApplyDTO;
import com.mini.shop.dao.generate.OmsOrderReturnApplyDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsOrderReturnApplyDTOMapper {
    long countByExample(OmsOrderReturnApplyDTOExample example);

    int deleteByExample(OmsOrderReturnApplyDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(OmsOrderReturnApplyDTO record);

    int insertSelective(OmsOrderReturnApplyDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OmsOrderReturnApplyDTO selectOneByExample(OmsOrderReturnApplyDTOExample example);

    List<OmsOrderReturnApplyDTO> selectByExample(OmsOrderReturnApplyDTOExample example);

    OmsOrderReturnApplyDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") OmsOrderReturnApplyDTO record, @Param("example") OmsOrderReturnApplyDTOExample example);

    int updateByExample(@Param("record") OmsOrderReturnApplyDTO record, @Param("example") OmsOrderReturnApplyDTOExample example);

    int updateByPrimaryKeySelective(OmsOrderReturnApplyDTO record);

    int updateByPrimaryKey(OmsOrderReturnApplyDTO record);
}