package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.OmsOrderItemDTO;
import com.mini.shop.dao.generate.OmsOrderItemDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsOrderItemDTOMapper {
    long countByExample(OmsOrderItemDTOExample example);

    int deleteByExample(OmsOrderItemDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(OmsOrderItemDTO record);

    int insertSelective(OmsOrderItemDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OmsOrderItemDTO selectOneByExample(OmsOrderItemDTOExample example);

    List<OmsOrderItemDTO> selectByExample(OmsOrderItemDTOExample example);

    OmsOrderItemDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") OmsOrderItemDTO record, @Param("example") OmsOrderItemDTOExample example);

    int updateByExample(@Param("record") OmsOrderItemDTO record, @Param("example") OmsOrderItemDTOExample example);

    int updateByPrimaryKeySelective(OmsOrderItemDTO record);

    int updateByPrimaryKey(OmsOrderItemDTO record);
}