package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.OmsOrderReturnReasonDTO;
import com.mini.shop.dao.generate.OmsOrderReturnReasonDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsOrderReturnReasonDTOMapper {
    long countByExample(OmsOrderReturnReasonDTOExample example);

    int deleteByExample(OmsOrderReturnReasonDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(OmsOrderReturnReasonDTO record);

    int insertSelective(OmsOrderReturnReasonDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_reason
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OmsOrderReturnReasonDTO selectOneByExample(OmsOrderReturnReasonDTOExample example);

    List<OmsOrderReturnReasonDTO> selectByExample(OmsOrderReturnReasonDTOExample example);

    OmsOrderReturnReasonDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") OmsOrderReturnReasonDTO record, @Param("example") OmsOrderReturnReasonDTOExample example);

    int updateByExample(@Param("record") OmsOrderReturnReasonDTO record, @Param("example") OmsOrderReturnReasonDTOExample example);

    int updateByPrimaryKeySelective(OmsOrderReturnReasonDTO record);

    int updateByPrimaryKey(OmsOrderReturnReasonDTO record);
}