package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsAlbumDTO;
import com.mini.shop.dao.generate.PmsAlbumDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsAlbumDTOMapper {
    long countByExample(PmsAlbumDTOExample example);

    int deleteByExample(PmsAlbumDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsAlbumDTO record);

    int insertSelective(PmsAlbumDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsAlbumDTO selectOneByExample(PmsAlbumDTOExample example);

    List<PmsAlbumDTO> selectByExample(PmsAlbumDTOExample example);

    PmsAlbumDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsAlbumDTO record, @Param("example") PmsAlbumDTOExample example);

    int updateByExample(@Param("record") PmsAlbumDTO record, @Param("example") PmsAlbumDTOExample example);

    int updateByPrimaryKeySelective(PmsAlbumDTO record);

    int updateByPrimaryKey(PmsAlbumDTO record);
}