package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsAlbumPicDTO;
import com.mini.shop.dao.generate.PmsAlbumPicDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsAlbumPicDTOMapper {
    long countByExample(PmsAlbumPicDTOExample example);

    int deleteByExample(PmsAlbumPicDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsAlbumPicDTO record);

    int insertSelective(PmsAlbumPicDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album_pic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsAlbumPicDTO selectOneByExample(PmsAlbumPicDTOExample example);

    List<PmsAlbumPicDTO> selectByExample(PmsAlbumPicDTOExample example);

    PmsAlbumPicDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsAlbumPicDTO record, @Param("example") PmsAlbumPicDTOExample example);

    int updateByExample(@Param("record") PmsAlbumPicDTO record, @Param("example") PmsAlbumPicDTOExample example);

    int updateByPrimaryKeySelective(PmsAlbumPicDTO record);

    int updateByPrimaryKey(PmsAlbumPicDTO record);
}