package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsBrandDTO;
import com.mini.shop.dao.generate.PmsBrandDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsBrandDTOMapper {
    long countByExample(PmsBrandDTOExample example);

    int deleteByExample(PmsBrandDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsBrandDTO record);

    int insertSelective(PmsBrandDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsBrandDTO selectOneByExample(PmsBrandDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsBrandDTO selectOneByExampleWithBLOBs(PmsBrandDTOExample example);

    List<PmsBrandDTO> selectByExampleWithBLOBs(PmsBrandDTOExample example);

    List<PmsBrandDTO> selectByExample(PmsBrandDTOExample example);

    PmsBrandDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsBrandDTO record, @Param("example") PmsBrandDTOExample example);

    int updateByExampleWithBLOBs(@Param("record") PmsBrandDTO record, @Param("example") PmsBrandDTOExample example);

    int updateByExample(@Param("record") PmsBrandDTO record, @Param("example") PmsBrandDTOExample example);

    int updateByPrimaryKeySelective(PmsBrandDTO record);

    int updateByPrimaryKeyWithBLOBs(PmsBrandDTO record);

    int updateByPrimaryKey(PmsBrandDTO record);
}