package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsCommentReplayDTO;
import com.mini.shop.dao.generate.PmsCommentReplayDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsCommentReplayDTOMapper {
    long countByExample(PmsCommentReplayDTOExample example);

    int deleteByExample(PmsCommentReplayDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsCommentReplayDTO record);

    int insertSelective(PmsCommentReplayDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsCommentReplayDTO selectOneByExample(PmsCommentReplayDTOExample example);

    List<PmsCommentReplayDTO> selectByExample(PmsCommentReplayDTOExample example);

    PmsCommentReplayDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsCommentReplayDTO record, @Param("example") PmsCommentReplayDTOExample example);

    int updateByExample(@Param("record") PmsCommentReplayDTO record, @Param("example") PmsCommentReplayDTOExample example);

    int updateByPrimaryKeySelective(PmsCommentReplayDTO record);

    int updateByPrimaryKey(PmsCommentReplayDTO record);
}