package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsFeightTemplateDTO;
import com.mini.shop.dao.generate.PmsFeightTemplateDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsFeightTemplateDTOMapper {
    long countByExample(PmsFeightTemplateDTOExample example);

    int deleteByExample(PmsFeightTemplateDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsFeightTemplateDTO record);

    int insertSelective(PmsFeightTemplateDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_feight_template
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsFeightTemplateDTO selectOneByExample(PmsFeightTemplateDTOExample example);

    List<PmsFeightTemplateDTO> selectByExample(PmsFeightTemplateDTOExample example);

    PmsFeightTemplateDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsFeightTemplateDTO record, @Param("example") PmsFeightTemplateDTOExample example);

    int updateByExample(@Param("record") PmsFeightTemplateDTO record, @Param("example") PmsFeightTemplateDTOExample example);

    int updateByPrimaryKeySelective(PmsFeightTemplateDTO record);

    int updateByPrimaryKey(PmsFeightTemplateDTO record);
}