package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsMemberPriceDTO;
import com.mini.shop.dao.generate.PmsMemberPriceDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsMemberPriceDTOMapper {
    long countByExample(PmsMemberPriceDTOExample example);

    int deleteByExample(PmsMemberPriceDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsMemberPriceDTO record);

    int insertSelective(PmsMemberPriceDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_member_price
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsMemberPriceDTO selectOneByExample(PmsMemberPriceDTOExample example);

    List<PmsMemberPriceDTO> selectByExample(PmsMemberPriceDTOExample example);

    PmsMemberPriceDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsMemberPriceDTO record, @Param("example") PmsMemberPriceDTOExample example);

    int updateByExample(@Param("record") PmsMemberPriceDTO record, @Param("example") PmsMemberPriceDTOExample example);

    int updateByPrimaryKeySelective(PmsMemberPriceDTO record);

    int updateByPrimaryKey(PmsMemberPriceDTO record);
}