package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsProductDTO;
import com.mini.shop.dao.generate.PmsProductDTOExample;
import com.mini.shop.dao.generate.PmsProductDTOWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductDTOMapper {
    long countByExample(PmsProductDTOExample example);

    int deleteByExample(PmsProductDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsProductDTOWithBLOBs record);

    int insertSelective(PmsProductDTOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsProductDTO selectOneByExample(PmsProductDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsProductDTOWithBLOBs selectOneByExampleWithBLOBs(PmsProductDTOExample example);

    List<PmsProductDTOWithBLOBs> selectByExampleWithBLOBs(PmsProductDTOExample example);

    List<PmsProductDTO> selectByExample(PmsProductDTOExample example);

    PmsProductDTOWithBLOBs selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsProductDTOWithBLOBs record, @Param("example") PmsProductDTOExample example);

    int updateByExampleWithBLOBs(@Param("record") PmsProductDTOWithBLOBs record, @Param("example") PmsProductDTOExample example);

    int updateByExample(@Param("record") PmsProductDTO record, @Param("example") PmsProductDTOExample example);

    int updateByPrimaryKeySelective(PmsProductDTOWithBLOBs record);

    int updateByPrimaryKeyWithBLOBs(PmsProductDTOWithBLOBs record);

    int updateByPrimaryKey(PmsProductDTO record);
}