package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsProductAttributeCategoryDTO;
import com.mini.shop.dao.generate.PmsProductAttributeCategoryDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductAttributeCategoryDTOMapper {
    long countByExample(PmsProductAttributeCategoryDTOExample example);

    int deleteByExample(PmsProductAttributeCategoryDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsProductAttributeCategoryDTO record);

    int insertSelective(PmsProductAttributeCategoryDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsProductAttributeCategoryDTO selectOneByExample(PmsProductAttributeCategoryDTOExample example);

    List<PmsProductAttributeCategoryDTO> selectByExample(PmsProductAttributeCategoryDTOExample example);

    PmsProductAttributeCategoryDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsProductAttributeCategoryDTO record, @Param("example") PmsProductAttributeCategoryDTOExample example);

    int updateByExample(@Param("record") PmsProductAttributeCategoryDTO record, @Param("example") PmsProductAttributeCategoryDTOExample example);

    int updateByPrimaryKeySelective(PmsProductAttributeCategoryDTO record);

    int updateByPrimaryKey(PmsProductAttributeCategoryDTO record);
}