package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsProductAttributeValueDTO;
import com.mini.shop.dao.generate.PmsProductAttributeValueDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductAttributeValueDTOMapper {
    long countByExample(PmsProductAttributeValueDTOExample example);

    int deleteByExample(PmsProductAttributeValueDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsProductAttributeValueDTO record);

    int insertSelective(PmsProductAttributeValueDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsProductAttributeValueDTO selectOneByExample(PmsProductAttributeValueDTOExample example);

    List<PmsProductAttributeValueDTO> selectByExample(PmsProductAttributeValueDTOExample example);

    PmsProductAttributeValueDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsProductAttributeValueDTO record, @Param("example") PmsProductAttributeValueDTOExample example);

    int updateByExample(@Param("record") PmsProductAttributeValueDTO record, @Param("example") PmsProductAttributeValueDTOExample example);

    int updateByPrimaryKeySelective(PmsProductAttributeValueDTO record);

    int updateByPrimaryKey(PmsProductAttributeValueDTO record);
}