package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsProductFullReductionDTO;
import com.mini.shop.dao.generate.PmsProductFullReductionDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductFullReductionDTOMapper {
    long countByExample(PmsProductFullReductionDTOExample example);

    int deleteByExample(PmsProductFullReductionDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsProductFullReductionDTO record);

    int insertSelective(PmsProductFullReductionDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsProductFullReductionDTO selectOneByExample(PmsProductFullReductionDTOExample example);

    List<PmsProductFullReductionDTO> selectByExample(PmsProductFullReductionDTOExample example);

    PmsProductFullReductionDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsProductFullReductionDTO record, @Param("example") PmsProductFullReductionDTOExample example);

    int updateByExample(@Param("record") PmsProductFullReductionDTO record, @Param("example") PmsProductFullReductionDTOExample example);

    int updateByPrimaryKeySelective(PmsProductFullReductionDTO record);

    int updateByPrimaryKey(PmsProductFullReductionDTO record);
}