package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.PmsProductCategoryDTO;
import com.mini.shop.dao.generate.PmsProductCategoryDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductCategoryDTOMapper {
    long countByExample(PmsProductCategoryDTOExample example);

    int deleteByExample(PmsProductCategoryDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PmsProductCategoryDTO record);

    int insertSelective(PmsProductCategoryDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsProductCategoryDTO selectOneByExample(PmsProductCategoryDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PmsProductCategoryDTO selectOneByExampleWithBLOBs(PmsProductCategoryDTOExample example);

    List<PmsProductCategoryDTO> selectByExampleWithBLOBs(PmsProductCategoryDTOExample example);

    List<PmsProductCategoryDTO> selectByExample(PmsProductCategoryDTOExample example);

    PmsProductCategoryDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PmsProductCategoryDTO record, @Param("example") PmsProductCategoryDTOExample example);

    int updateByExampleWithBLOBs(@Param("record") PmsProductCategoryDTO record, @Param("example") PmsProductCategoryDTOExample example);

    int updateByExample(@Param("record") PmsProductCategoryDTO record, @Param("example") PmsProductCategoryDTOExample example);

    int updateByPrimaryKeySelective(PmsProductCategoryDTO record);

    int updateByPrimaryKeyWithBLOBs(PmsProductCategoryDTO record);

    int updateByPrimaryKey(PmsProductCategoryDTO record);
}