package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.SmsCouponHistoryDTO;
import com.mini.shop.dao.generate.SmsCouponHistoryDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsCouponHistoryDTOMapper {
    long countByExample(SmsCouponHistoryDTOExample example);

    int deleteByExample(SmsCouponHistoryDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SmsCouponHistoryDTO record);

    int insertSelective(SmsCouponHistoryDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmsCouponHistoryDTO selectOneByExample(SmsCouponHistoryDTOExample example);

    List<SmsCouponHistoryDTO> selectByExample(SmsCouponHistoryDTOExample example);

    SmsCouponHistoryDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SmsCouponHistoryDTO record, @Param("example") SmsCouponHistoryDTOExample example);

    int updateByExample(@Param("record") SmsCouponHistoryDTO record, @Param("example") SmsCouponHistoryDTOExample example);

    int updateByPrimaryKeySelective(SmsCouponHistoryDTO record);

    int updateByPrimaryKey(SmsCouponHistoryDTO record);
}