package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.SmsCouponDTO;
import com.mini.shop.dao.generate.SmsCouponDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsCouponDTOMapper {
    long countByExample(SmsCouponDTOExample example);

    int deleteByExample(SmsCouponDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SmsCouponDTO record);

    int insertSelective(SmsCouponDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmsCouponDTO selectOneByExample(SmsCouponDTOExample example);

    List<SmsCouponDTO> selectByExample(SmsCouponDTOExample example);

    SmsCouponDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SmsCouponDTO record, @Param("example") SmsCouponDTOExample example);

    int updateByExample(@Param("record") SmsCouponDTO record, @Param("example") SmsCouponDTOExample example);

    int updateByPrimaryKeySelective(SmsCouponDTO record);

    int updateByPrimaryKey(SmsCouponDTO record);
}