package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.SmsCouponProductRelationDTO;
import com.mini.shop.dao.generate.SmsCouponProductRelationDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsCouponProductRelationDTOMapper {
    long countByExample(SmsCouponProductRelationDTOExample example);

    int deleteByExample(SmsCouponProductRelationDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SmsCouponProductRelationDTO record);

    int insertSelective(SmsCouponProductRelationDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmsCouponProductRelationDTO selectOneByExample(SmsCouponProductRelationDTOExample example);

    List<SmsCouponProductRelationDTO> selectByExample(SmsCouponProductRelationDTOExample example);

    SmsCouponProductRelationDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SmsCouponProductRelationDTO record, @Param("example") SmsCouponProductRelationDTOExample example);

    int updateByExample(@Param("record") SmsCouponProductRelationDTO record, @Param("example") SmsCouponProductRelationDTOExample example);

    int updateByPrimaryKeySelective(SmsCouponProductRelationDTO record);

    int updateByPrimaryKey(SmsCouponProductRelationDTO record);
}