package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.SmsFlashPromotionProductRelationDTO;
import com.mini.shop.dao.generate.SmsFlashPromotionProductRelationDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsFlashPromotionProductRelationDTOMapper {
    long countByExample(SmsFlashPromotionProductRelationDTOExample example);

    int deleteByExample(SmsFlashPromotionProductRelationDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SmsFlashPromotionProductRelationDTO record);

    int insertSelective(SmsFlashPromotionProductRelationDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_product_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmsFlashPromotionProductRelationDTO selectOneByExample(SmsFlashPromotionProductRelationDTOExample example);

    List<SmsFlashPromotionProductRelationDTO> selectByExample(SmsFlashPromotionProductRelationDTOExample example);

    SmsFlashPromotionProductRelationDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SmsFlashPromotionProductRelationDTO record, @Param("example") SmsFlashPromotionProductRelationDTOExample example);

    int updateByExample(@Param("record") SmsFlashPromotionProductRelationDTO record, @Param("example") SmsFlashPromotionProductRelationDTOExample example);

    int updateByPrimaryKeySelective(SmsFlashPromotionProductRelationDTO record);

    int updateByPrimaryKey(SmsFlashPromotionProductRelationDTO record);
}