package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.SmsFlashPromotionLogDTO;
import com.mini.shop.dao.generate.SmsFlashPromotionLogDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsFlashPromotionLogDTOMapper {
    long countByExample(SmsFlashPromotionLogDTOExample example);

    int deleteByExample(SmsFlashPromotionLogDTOExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(SmsFlashPromotionLogDTO record);

    int insertSelective(SmsFlashPromotionLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmsFlashPromotionLogDTO selectOneByExample(SmsFlashPromotionLogDTOExample example);

    List<SmsFlashPromotionLogDTO> selectByExample(SmsFlashPromotionLogDTOExample example);

    SmsFlashPromotionLogDTO selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") SmsFlashPromotionLogDTO record, @Param("example") SmsFlashPromotionLogDTOExample example);

    int updateByExample(@Param("record") SmsFlashPromotionLogDTO record, @Param("example") SmsFlashPromotionLogDTOExample example);

    int updateByPrimaryKeySelective(SmsFlashPromotionLogDTO record);

    int updateByPrimaryKey(SmsFlashPromotionLogDTO record);
}