package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.SmsHomeRecommendProductDTO;
import com.mini.shop.dao.generate.SmsHomeRecommendProductDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsHomeRecommendProductDTOMapper {
    long countByExample(SmsHomeRecommendProductDTOExample example);

    int deleteByExample(SmsHomeRecommendProductDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SmsHomeRecommendProductDTO record);

    int insertSelective(SmsHomeRecommendProductDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmsHomeRecommendProductDTO selectOneByExample(SmsHomeRecommendProductDTOExample example);

    List<SmsHomeRecommendProductDTO> selectByExample(SmsHomeRecommendProductDTOExample example);

    SmsHomeRecommendProductDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SmsHomeRecommendProductDTO record, @Param("example") SmsHomeRecommendProductDTOExample example);

    int updateByExample(@Param("record") SmsHomeRecommendProductDTO record, @Param("example") SmsHomeRecommendProductDTOExample example);

    int updateByPrimaryKeySelective(SmsHomeRecommendProductDTO record);

    int updateByPrimaryKey(SmsHomeRecommendProductDTO record);
}