package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.SmsHomeNewProductDTO;
import com.mini.shop.dao.generate.SmsHomeNewProductDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsHomeNewProductDTOMapper {
    long countByExample(SmsHomeNewProductDTOExample example);

    int deleteByExample(SmsHomeNewProductDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SmsHomeNewProductDTO record);

    int insertSelective(SmsHomeNewProductDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmsHomeNewProductDTO selectOneByExample(SmsHomeNewProductDTOExample example);

    List<SmsHomeNewProductDTO> selectByExample(SmsHomeNewProductDTOExample example);

    SmsHomeNewProductDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SmsHomeNewProductDTO record, @Param("example") SmsHomeNewProductDTOExample example);

    int updateByExample(@Param("record") SmsHomeNewProductDTO record, @Param("example") SmsHomeNewProductDTOExample example);

    int updateByPrimaryKeySelective(SmsHomeNewProductDTO record);

    int updateByPrimaryKey(SmsHomeNewProductDTO record);
}