package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.SmsHomeBrandDTO;
import com.mini.shop.dao.generate.SmsHomeBrandDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsHomeBrandDTOMapper {
    long countByExample(SmsHomeBrandDTOExample example);

    int deleteByExample(SmsHomeBrandDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SmsHomeBrandDTO record);

    int insertSelective(SmsHomeBrandDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmsHomeBrandDTO selectOneByExample(SmsHomeBrandDTOExample example);

    List<SmsHomeBrandDTO> selectByExample(SmsHomeBrandDTOExample example);

    SmsHomeBrandDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SmsHomeBrandDTO record, @Param("example") SmsHomeBrandDTOExample example);

    int updateByExample(@Param("record") SmsHomeBrandDTO record, @Param("example") SmsHomeBrandDTOExample example);

    int updateByPrimaryKeySelective(SmsHomeBrandDTO record);

    int updateByPrimaryKey(SmsHomeBrandDTO record);
}