package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.SmsHomeRecommendSubjectDTO;
import com.mini.shop.dao.generate.SmsHomeRecommendSubjectDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsHomeRecommendSubjectDTOMapper {
    long countByExample(SmsHomeRecommendSubjectDTOExample example);

    int deleteByExample(SmsHomeRecommendSubjectDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SmsHomeRecommendSubjectDTO record);

    int insertSelective(SmsHomeRecommendSubjectDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_subject
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmsHomeRecommendSubjectDTO selectOneByExample(SmsHomeRecommendSubjectDTOExample example);

    List<SmsHomeRecommendSubjectDTO> selectByExample(SmsHomeRecommendSubjectDTOExample example);

    SmsHomeRecommendSubjectDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SmsHomeRecommendSubjectDTO record, @Param("example") SmsHomeRecommendSubjectDTOExample example);

    int updateByExample(@Param("record") SmsHomeRecommendSubjectDTO record, @Param("example") SmsHomeRecommendSubjectDTOExample example);

    int updateByPrimaryKeySelective(SmsHomeRecommendSubjectDTO record);

    int updateByPrimaryKey(SmsHomeRecommendSubjectDTO record);
}