package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsAdminRoleRelationDTO;
import com.mini.shop.dao.generate.UmsAdminRoleRelationDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsAdminRoleRelationDTOMapper {
    long countByExample(UmsAdminRoleRelationDTOExample example);

    int deleteByExample(UmsAdminRoleRelationDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsAdminRoleRelationDTO record);

    int insertSelective(UmsAdminRoleRelationDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_role_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsAdminRoleRelationDTO selectOneByExample(UmsAdminRoleRelationDTOExample example);

    List<UmsAdminRoleRelationDTO> selectByExample(UmsAdminRoleRelationDTOExample example);

    UmsAdminRoleRelationDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsAdminRoleRelationDTO record, @Param("example") UmsAdminRoleRelationDTOExample example);

    int updateByExample(@Param("record") UmsAdminRoleRelationDTO record, @Param("example") UmsAdminRoleRelationDTOExample example);

    int updateByPrimaryKeySelective(UmsAdminRoleRelationDTO record);

    int updateByPrimaryKey(UmsAdminRoleRelationDTO record);
}