package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsAdminLoginLogDTO;
import com.mini.shop.dao.generate.UmsAdminLoginLogDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsAdminLoginLogDTOMapper {
    long countByExample(UmsAdminLoginLogDTOExample example);

    int deleteByExample(UmsAdminLoginLogDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsAdminLoginLogDTO record);

    int insertSelective(UmsAdminLoginLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsAdminLoginLogDTO selectOneByExample(UmsAdminLoginLogDTOExample example);

    List<UmsAdminLoginLogDTO> selectByExample(UmsAdminLoginLogDTOExample example);

    UmsAdminLoginLogDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsAdminLoginLogDTO record, @Param("example") UmsAdminLoginLogDTOExample example);

    int updateByExample(@Param("record") UmsAdminLoginLogDTO record, @Param("example") UmsAdminLoginLogDTOExample example);

    int updateByPrimaryKeySelective(UmsAdminLoginLogDTO record);

    int updateByPrimaryKey(UmsAdminLoginLogDTO record);
}