package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsAdminPermissionRelationDTO;
import com.mini.shop.dao.generate.UmsAdminPermissionRelationDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsAdminPermissionRelationDTOMapper {
    long countByExample(UmsAdminPermissionRelationDTOExample example);

    int deleteByExample(UmsAdminPermissionRelationDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsAdminPermissionRelationDTO record);

    int insertSelective(UmsAdminPermissionRelationDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsAdminPermissionRelationDTO selectOneByExample(UmsAdminPermissionRelationDTOExample example);

    List<UmsAdminPermissionRelationDTO> selectByExample(UmsAdminPermissionRelationDTOExample example);

    UmsAdminPermissionRelationDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsAdminPermissionRelationDTO record, @Param("example") UmsAdminPermissionRelationDTOExample example);

    int updateByExample(@Param("record") UmsAdminPermissionRelationDTO record, @Param("example") UmsAdminPermissionRelationDTOExample example);

    int updateByPrimaryKeySelective(UmsAdminPermissionRelationDTO record);

    int updateByPrimaryKey(UmsAdminPermissionRelationDTO record);
}