package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsIntegrationChangeHistoryDTO;
import com.mini.shop.dao.generate.UmsIntegrationChangeHistoryDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsIntegrationChangeHistoryDTOMapper {
    long countByExample(UmsIntegrationChangeHistoryDTOExample example);

    int deleteByExample(UmsIntegrationChangeHistoryDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsIntegrationChangeHistoryDTO record);

    int insertSelective(UmsIntegrationChangeHistoryDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_integration_change_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsIntegrationChangeHistoryDTO selectOneByExample(UmsIntegrationChangeHistoryDTOExample example);

    List<UmsIntegrationChangeHistoryDTO> selectByExample(UmsIntegrationChangeHistoryDTOExample example);

    UmsIntegrationChangeHistoryDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsIntegrationChangeHistoryDTO record, @Param("example") UmsIntegrationChangeHistoryDTOExample example);

    int updateByExample(@Param("record") UmsIntegrationChangeHistoryDTO record, @Param("example") UmsIntegrationChangeHistoryDTOExample example);

    int updateByPrimaryKeySelective(UmsIntegrationChangeHistoryDTO record);

    int updateByPrimaryKey(UmsIntegrationChangeHistoryDTO record);
}