package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsIntegrationConsumeSettingDTO;
import com.mini.shop.dao.generate.UmsIntegrationConsumeSettingDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsIntegrationConsumeSettingDTOMapper {
    long countByExample(UmsIntegrationConsumeSettingDTOExample example);

    int deleteByExample(UmsIntegrationConsumeSettingDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsIntegrationConsumeSettingDTO record);

    int insertSelective(UmsIntegrationConsumeSettingDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_integration_consume_setting
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsIntegrationConsumeSettingDTO selectOneByExample(UmsIntegrationConsumeSettingDTOExample example);

    List<UmsIntegrationConsumeSettingDTO> selectByExample(UmsIntegrationConsumeSettingDTOExample example);

    UmsIntegrationConsumeSettingDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsIntegrationConsumeSettingDTO record, @Param("example") UmsIntegrationConsumeSettingDTOExample example);

    int updateByExample(@Param("record") UmsIntegrationConsumeSettingDTO record, @Param("example") UmsIntegrationConsumeSettingDTOExample example);

    int updateByPrimaryKeySelective(UmsIntegrationConsumeSettingDTO record);

    int updateByPrimaryKey(UmsIntegrationConsumeSettingDTO record);
}