package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsMemberStatisticsInfoDTO;
import com.mini.shop.dao.generate.UmsMemberStatisticsInfoDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberStatisticsInfoDTOMapper {
    long countByExample(UmsMemberStatisticsInfoDTOExample example);

    int deleteByExample(UmsMemberStatisticsInfoDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsMemberStatisticsInfoDTO record);

    int insertSelective(UmsMemberStatisticsInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsMemberStatisticsInfoDTO selectOneByExample(UmsMemberStatisticsInfoDTOExample example);

    List<UmsMemberStatisticsInfoDTO> selectByExample(UmsMemberStatisticsInfoDTOExample example);

    UmsMemberStatisticsInfoDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsMemberStatisticsInfoDTO record, @Param("example") UmsMemberStatisticsInfoDTOExample example);

    int updateByExample(@Param("record") UmsMemberStatisticsInfoDTO record, @Param("example") UmsMemberStatisticsInfoDTOExample example);

    int updateByPrimaryKeySelective(UmsMemberStatisticsInfoDTO record);

    int updateByPrimaryKey(UmsMemberStatisticsInfoDTO record);
}