package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsMemberProductCategoryRelationDTO;
import com.mini.shop.dao.generate.UmsMemberProductCategoryRelationDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberProductCategoryRelationDTOMapper {
    long countByExample(UmsMemberProductCategoryRelationDTOExample example);

    int deleteByExample(UmsMemberProductCategoryRelationDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsMemberProductCategoryRelationDTO record);

    int insertSelective(UmsMemberProductCategoryRelationDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_product_category_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsMemberProductCategoryRelationDTO selectOneByExample(UmsMemberProductCategoryRelationDTOExample example);

    List<UmsMemberProductCategoryRelationDTO> selectByExample(UmsMemberProductCategoryRelationDTOExample example);

    UmsMemberProductCategoryRelationDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsMemberProductCategoryRelationDTO record, @Param("example") UmsMemberProductCategoryRelationDTOExample example);

    int updateByExample(@Param("record") UmsMemberProductCategoryRelationDTO record, @Param("example") UmsMemberProductCategoryRelationDTOExample example);

    int updateByPrimaryKeySelective(UmsMemberProductCategoryRelationDTO record);

    int updateByPrimaryKey(UmsMemberProductCategoryRelationDTO record);
}