package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsMemberReceiveAddressDTO;
import com.mini.shop.dao.generate.UmsMemberReceiveAddressDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberReceiveAddressDTOMapper {
    long countByExample(UmsMemberReceiveAddressDTOExample example);

    int deleteByExample(UmsMemberReceiveAddressDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsMemberReceiveAddressDTO record);

    int insertSelective(UmsMemberReceiveAddressDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_receive_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsMemberReceiveAddressDTO selectOneByExample(UmsMemberReceiveAddressDTOExample example);

    List<UmsMemberReceiveAddressDTO> selectByExample(UmsMemberReceiveAddressDTOExample example);

    UmsMemberReceiveAddressDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsMemberReceiveAddressDTO record, @Param("example") UmsMemberReceiveAddressDTOExample example);

    int updateByExample(@Param("record") UmsMemberReceiveAddressDTO record, @Param("example") UmsMemberReceiveAddressDTOExample example);

    int updateByPrimaryKeySelective(UmsMemberReceiveAddressDTO record);

    int updateByPrimaryKey(UmsMemberReceiveAddressDTO record);
}