package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsMemberLevelDTO;
import com.mini.shop.dao.generate.UmsMemberLevelDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberLevelDTOMapper {
    long countByExample(UmsMemberLevelDTOExample example);

    int deleteByExample(UmsMemberLevelDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsMemberLevelDTO record);

    int insertSelective(UmsMemberLevelDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsMemberLevelDTO selectOneByExample(UmsMemberLevelDTOExample example);

    List<UmsMemberLevelDTO> selectByExample(UmsMemberLevelDTOExample example);

    UmsMemberLevelDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsMemberLevelDTO record, @Param("example") UmsMemberLevelDTOExample example);

    int updateByExample(@Param("record") UmsMemberLevelDTO record, @Param("example") UmsMemberLevelDTOExample example);

    int updateByPrimaryKeySelective(UmsMemberLevelDTO record);

    int updateByPrimaryKey(UmsMemberLevelDTO record);
}