package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsMemberRuleSettingDTO;
import com.mini.shop.dao.generate.UmsMemberRuleSettingDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberRuleSettingDTOMapper {
    long countByExample(UmsMemberRuleSettingDTOExample example);

    int deleteByExample(UmsMemberRuleSettingDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsMemberRuleSettingDTO record);

    int insertSelective(UmsMemberRuleSettingDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsMemberRuleSettingDTO selectOneByExample(UmsMemberRuleSettingDTOExample example);

    List<UmsMemberRuleSettingDTO> selectByExample(UmsMemberRuleSettingDTOExample example);

    UmsMemberRuleSettingDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsMemberRuleSettingDTO record, @Param("example") UmsMemberRuleSettingDTOExample example);

    int updateByExample(@Param("record") UmsMemberRuleSettingDTO record, @Param("example") UmsMemberRuleSettingDTOExample example);

    int updateByPrimaryKeySelective(UmsMemberRuleSettingDTO record);

    int updateByPrimaryKey(UmsMemberRuleSettingDTO record);
}