package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsPermissionDTO;
import com.mini.shop.dao.generate.UmsPermissionDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsPermissionDTOMapper {
    long countByExample(UmsPermissionDTOExample example);

    int deleteByExample(UmsPermissionDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsPermissionDTO record);

    int insertSelective(UmsPermissionDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsPermissionDTO selectOneByExample(UmsPermissionDTOExample example);

    List<UmsPermissionDTO> selectByExample(UmsPermissionDTOExample example);

    UmsPermissionDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsPermissionDTO record, @Param("example") UmsPermissionDTOExample example);

    int updateByExample(@Param("record") UmsPermissionDTO record, @Param("example") UmsPermissionDTOExample example);

    int updateByPrimaryKeySelective(UmsPermissionDTO record);

    int updateByPrimaryKey(UmsPermissionDTO record);
}