package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsRolePermissionRelationDTO;
import com.mini.shop.dao.generate.UmsRolePermissionRelationDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsRolePermissionRelationDTOMapper {
    long countByExample(UmsRolePermissionRelationDTOExample example);

    int deleteByExample(UmsRolePermissionRelationDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsRolePermissionRelationDTO record);

    int insertSelective(UmsRolePermissionRelationDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsRolePermissionRelationDTO selectOneByExample(UmsRolePermissionRelationDTOExample example);

    List<UmsRolePermissionRelationDTO> selectByExample(UmsRolePermissionRelationDTOExample example);

    UmsRolePermissionRelationDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsRolePermissionRelationDTO record, @Param("example") UmsRolePermissionRelationDTOExample example);

    int updateByExample(@Param("record") UmsRolePermissionRelationDTO record, @Param("example") UmsRolePermissionRelationDTOExample example);

    int updateByPrimaryKeySelective(UmsRolePermissionRelationDTO record);

    int updateByPrimaryKey(UmsRolePermissionRelationDTO record);
}