package com.mini.shop.mapper.generatedMapper;

import com.mini.shop.dao.generate.UmsRoleDTO;
import com.mini.shop.dao.generate.UmsRoleDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsRoleDTOMapper {
    long countByExample(UmsRoleDTOExample example);

    int deleteByExample(UmsRoleDTOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UmsRoleDTO record);

    int insertSelective(UmsRoleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UmsRoleDTO selectOneByExample(UmsRoleDTOExample example);

    List<UmsRoleDTO> selectByExample(UmsRoleDTOExample example);

    UmsRoleDTO selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UmsRoleDTO record, @Param("example") UmsRoleDTOExample example);

    int updateByExample(@Param("record") UmsRoleDTO record, @Param("example") UmsRoleDTOExample example);

    int updateByPrimaryKeySelective(UmsRoleDTO record);

    int updateByPrimaryKey(UmsRoleDTO record);
}